version: "3.3"

services:
  caddy:
    image: davidtca/caddy-discord:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - $PWD/caddy/Caddyfile-dev:/etc/caddy/Caddyfile
  nolocal:
    build: .
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass root
    working_dir: /rdb
    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"