spring:
  profiles:
    active: production
logging:
  path: /var/log
  level:
    root: ERROR
    org.springframework: WARN
    com.datocal.nolocal: INFO
    reactor.netty.http.client: DEBUG
discord:
  api:
    host: https://discord.com
    base-endpoint: /api/v8/applications
    secret: ${DISCORD_TOKEN:dummy-token}
    client-id: 899356200745984010
    guild-id: 1132336831149641898
    guild-mode: true
redis:
  host: redis
  port: 6379