name: Generate docs
on:
  workflow_dispatch:

jobs:
  BuildDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Build docs
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-git-revision-date-localized-plugin
          cp docs/architecture/c4model.html docs/devguide/c4model.md
          mkdocs build
      - name: Upload docs
        uses: actions/upload-artifact@v3.1.2
        with:
          path: site/
          name: documentation
      - name: Github Pages Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: site/
          publish_branch: github-actions
