name: Mutation Tests
on:
  workflow_dispatch:

jobs:
  Mutation-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.9.0
        with:
          version: 1.5.31
      - name: Mutation test run
        run: | 
           chmod +x ./gradlew
           SPRING_PROFILES_ACTIVE=test ./gradlew pitest
      - name: Publish Test Report
        if: always()
        uses: actions/upload-artifact@v4.3.0
        with:
          name: 'mutation-report'
          path: build/reports/pitest/*
